import { useState, useEffect, useCallback } from "react";
import { useParams, useNavigate, useSearchParams } from "react-router-dom";
import { Loader2, CheckCircle, XCircle, Clock, AlertTriangle, CreditCard } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Footer } from "@/components/layout/Footer";
import { bookingApi } from "@/services/bookingApi";
import { useBookingStore } from "@/stores/bookingStore";
import { toast } from "@/hooks/use-toast";
import type { BookingStatusValue } from "@/types/etgBooking";

const MAX_POLL_ATTEMPTS = 60; // 5 minutes at 5s intervals
const POLL_INTERVAL_MS = 5000; // 5 seconds per API recommendation

type ProcessingStatus = "polling" | "3ds" | "confirmed" | "failed" | "timeout";

/**
 * Get user-friendly error message for each status code
 */
function getStatusErrorMessage(status: BookingStatusValue, errorMessage?: string): string {
  switch (status) {
    case "block":
      return "Card payment could not be processed. Please try a different card.";
    case "charge":
      return "Card was declined. Please check your card details or try a different payment method.";
    case "soldout":
      return "This room is no longer available. Please search for alternative options.";
    case "provider":
      return "A temporary error occurred with the hotel. Please try again in a few minutes.";
    case "book_limit":
      return "Booking limit reached for this property. Please try again later.";
    case "not_allowed":
      return "This booking cannot be processed. Please contact support.";
    case "booking_finish_did_not_succeed":
      return "Booking could not be completed. Please try again.";
    case "timeout":
      return "The request timed out. We're still checking the status...";
    case "error":
    case "failed":
      return errorMessage || "An unexpected error occurred. Please try again.";
    default:
      return errorMessage || "An unexpected error occurred. Please try again or contact support.";
  }
}

/**
 * Handle 3DS redirect - submits form to bank ACS
 */
function handle3DSRedirect(data3ds: { 
  action_url: string; 
  method: "get" | "post"; 
  data: Record<string, string>;
}) {
  console.log("🔐 Initiating 3DS redirect to:", data3ds.action_url);
  
  if (data3ds.method === "get") {
    // For GET, append params to URL and redirect
    const url = new URL(data3ds.action_url);
    Object.entries(data3ds.data || {}).forEach(([key, value]) => {
      url.searchParams.append(key, value);
    });
    window.location.href = url.toString();
  } else {
    // For POST, create and submit a hidden form
    const form = document.createElement("form");
    form.method = "POST";
    form.action = data3ds.action_url;
    
    Object.entries(data3ds.data || {}).forEach(([key, value]) => {
      const input = document.createElement("input");
      input.type = "hidden";
      input.name = key;
      input.value = value;
      form.appendChild(input);
    });
    
    document.body.appendChild(form);
    form.submit();
  }
}

export default function ProcessingPage() {
  // RateHawk requires partner_order_id for status polling
  const { partnerOrderId } = useParams<{ partnerOrderId: string }>();
  const [urlSearchParams] = useSearchParams();
  const navigate = useNavigate();
  const { setOrderId, setOrderStatus } = useBookingStore();

  // Extract ETG order_id from query params (for confirmation page navigation)
  const etgOrderId = urlSearchParams.get("order_id");
  
  // Check if returning from 3DS redirect (bank adds these params)
  const is3DSReturn = urlSearchParams.has("MD") || urlSearchParams.has("PaRes");

  const [status, setStatus] = useState<ProcessingStatus>("polling");
  const [attempts, setAttempts] = useState(0);
  const [progressPercent, setProgressPercent] = useState<number>(0);
  const [confirmationNumber, setConfirmationNumber] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const pollStatus = useCallback(async () => {
    if (!partnerOrderId) {
      setStatus("failed");
      setErrorMessage("No order ID provided");
      return;
    }

    // Detect obviously fake order IDs (generated by frontend simulation)
    if (partnerOrderId.startsWith('ORD-') && /^ORD-\d+$/.test(partnerOrderId)) {
      setStatus("failed");
      setErrorMessage("Invalid booking reference. This appears to be a test order. Please start a new booking.");
      return;
    }

    if (is3DSReturn) {
      console.log("🔐 Returning from 3DS verification, resuming status polling...");
    }

    const startTime = Date.now();
    const maxWaitTimeMs = MAX_POLL_ATTEMPTS * POLL_INTERVAL_MS;
    let currentAttempt = 0;

    while (currentAttempt < MAX_POLL_ATTEMPTS) {
      currentAttempt++;
      setAttempts(currentAttempt);

      try {
        const response = await bookingApi.getOrderStatus(partnerOrderId);
        const data = response.data;
        
        // Update progress from API response
        if (data?.percent !== undefined) {
          setProgressPercent(data.percent);
        } else {
          // Fallback: calculate from attempts
          setProgressPercent(Math.min((currentAttempt / MAX_POLL_ATTEMPTS) * 100, 95));
        }

        console.log(`📊 Status poll #${currentAttempt}:`, {
          status: data?.status,
          is_final: data?.is_final,
          is_success: data?.is_success,
          is_processing: data?.is_processing,
          percent: data?.percent,
        });

        // ✅ SUCCESS: Booking confirmed
        if (data?.is_success || data?.status === "ok") {
          setStatus("confirmed");
          setProgressPercent(100);
          const displayId = etgOrderId || data?.partner_order_id || partnerOrderId;
          setConfirmationNumber(data?.confirmation_number || displayId);
          setOrderId(etgOrderId || partnerOrderId);
          setOrderStatus("confirmed");
          
          // Clear pending booking from session
          sessionStorage.removeItem("pending_booking");
          
          toast({
            title: "Booking Confirmed!",
            description: `Confirmation: ${data?.confirmation_number || displayId}`,
          });
          
          return;
        }

        // 🔐 3D SECURE: Requires user action
        if (data?.status === "3ds" && data?.data_3ds) {
          setStatus("3ds");
          // Small delay to show 3DS UI state before redirect
          await new Promise(r => setTimeout(r, 500));
          handle3DSRedirect(data.data_3ds);
          return; // Stop polling - browser will redirect
        }

        // ❌ FINAL ERROR: Booking failed
        if (data?.is_final && !data?.is_success) {
          const statusCode = data?.status || "error";
          const userMessage = getStatusErrorMessage(
            statusCode as BookingStatusValue,
            data?.error?.message || response.error?.message
          );
          setStatus("failed");
          setErrorMessage(userMessage);
          setOrderStatus("failed");
          console.log(`❌ Final failure: ${statusCode} - ${userMessage}`);
          return;
        }

        // ⏳ STILL PROCESSING: Check timeout and continue polling
        const elapsed = Date.now() - startTime;
        const timeRemaining = maxWaitTimeMs - elapsed;

        if (timeRemaining <= POLL_INTERVAL_MS && timeRemaining > 0) {
          // Final request before timeout (per API recommendation)
          console.log("⏱️ Sending final status check before timeout...");
          continue;
        }

        if (timeRemaining <= 0) {
          // Timeout reached
          setStatus("timeout");
          setOrderStatus("processing");
          return;
        }

        // Continue polling if still processing
        if (data?.is_processing || data?.status === "processing" || data?.status === "3ds") {
          await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
          continue;
        }

        // Unknown status - treat as processing and continue
        console.warn(`⚠️ Unknown status: ${data?.status}, continuing to poll...`);
        await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
        
      } catch (error) {
        console.error(`Poll attempt ${currentAttempt} error:`, error);
        
        const errorMsg = error instanceof Error ? error.message : String(error);
        
        // Check for invalid order ID errors - don't retry these
        if (
          errorMsg.includes('simulated/test order ID') ||
          errorMsg.includes('Invalid order ID format') ||
          errorMsg.includes('ORDER_STATUS_ERROR') ||
          errorMsg.includes('not found') ||
          errorMsg.includes('404')
        ) {
          setStatus("failed");
          setErrorMessage("Invalid booking reference. This may be a test order that wasn't processed by the server.");
          return;
        }
        
        // Network/server errors - wait and retry if we have time
        const elapsed = Date.now() - startTime;
        const timeRemaining = maxWaitTimeMs - elapsed;
        
        if (timeRemaining > POLL_INTERVAL_MS) {
          console.warn(`⚠️ Error polling status, retrying in ${POLL_INTERVAL_MS}ms...`);
          await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
          continue;
        }
        
        // Timeout on error
        setStatus("timeout");
        setOrderStatus("processing");
        return;
      }
    }

    // Max attempts reached
    setStatus("timeout");
    setOrderStatus("processing");
    
  }, [partnerOrderId, etgOrderId, is3DSReturn, setOrderId, setOrderStatus]);

  useEffect(() => {
    pollStatus();
  }, [pollStatus]);

  const handleRetry = () => {
    setStatus("polling");
    setAttempts(0);
    setProgressPercent(0);
    setErrorMessage(null);
    pollStatus();
  };

  const handleViewConfirmation = () => {
    const orderIdForConfirmation = etgOrderId || partnerOrderId;
    navigate(`/orders/${orderIdForConfirmation}/confirmation`);
  };

  const handleGoToDashboard = () => {
    navigate("/dashboard");
  };

  const handleContactSupport = () => {
    window.location.href = `mailto:support@travelhub.com?subject=Booking Issue - Order ${partnerOrderId}`;
  };

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <main className="flex-1 flex items-center justify-center p-4">
        <Card className="max-w-md w-full border-0 shadow-xl">
          <CardContent className="p-8">
            {/* Polling State */}
            {status === "polling" && (
              <div className="text-center">
                <div className="w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-6">
                  <Loader2 className="w-10 h-10 text-primary animate-spin" />
                </div>
                <h1 className="font-heading text-2xl font-bold text-foreground mb-2">
                  Processing Your Booking
                </h1>
                <p className="text-muted-foreground mb-6">
                  Please wait while we confirm your reservation...
                </p>
                
                <div className="space-y-2">
                  <Progress value={progressPercent} className="h-2" />
                  <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
                    <Clock className="h-4 w-4" />
                    <span>
                      {progressPercent > 0 
                        ? `${Math.round(progressPercent)}% complete`
                        : `Checking status... (${attempts}/${MAX_POLL_ATTEMPTS})`
                      }
                    </span>
                  </div>
                </div>

                <p className="text-xs text-muted-foreground mt-6">
                  This may take up to a minute. Please don't close this page.
                </p>
              </div>
            )}

            {/* 3DS Authentication State */}
            {status === "3ds" && (
              <div className="text-center">
                <div className="w-20 h-20 rounded-full bg-blue-500/10 flex items-center justify-center mx-auto mb-6">
                  <CreditCard className="w-10 h-10 text-blue-500" />
                </div>
                <h1 className="font-heading text-2xl font-bold text-foreground mb-2">
                  Card Verification Required
                </h1>
                <p className="text-muted-foreground mb-6">
                  Redirecting you to your bank for secure authentication...
                </p>
                
                <div className="flex items-center justify-center">
                  <Loader2 className="w-6 h-6 text-blue-500 animate-spin" />
                </div>

                <p className="text-xs text-muted-foreground mt-6">
                  You'll be redirected back after verification.
                </p>
              </div>
            )}

            {/* Confirmed State */}
            {status === "confirmed" && (
              <div className="text-center">
                <div className="w-20 h-20 rounded-full bg-emerald-500/10 flex items-center justify-center mx-auto mb-6">
                  <CheckCircle className="w-10 h-10 text-emerald-500" />
                </div>
                <h1 className="font-heading text-2xl font-bold text-foreground mb-2">
                  Booking Confirmed!
                </h1>
                <p className="text-muted-foreground mb-4">
                  Your reservation has been successfully confirmed.
                </p>
                
                {confirmationNumber && (
                  <div className="bg-primary/5 border border-primary/20 rounded-lg p-4 mb-6">
                    <p className="text-sm text-muted-foreground">Confirmation Number</p>
                    <p className="font-heading text-xl text-primary font-bold">
                      {confirmationNumber}
                    </p>
                  </div>
                )}

                <div className="space-y-3">
                  <Button onClick={handleViewConfirmation} className="w-full">
                    View Confirmation Details
                  </Button>
                  <Button variant="outline" onClick={handleGoToDashboard} className="w-full">
                    Go to Dashboard
                  </Button>
                </div>
              </div>
            )}

            {/* Failed State */}
            {status === "failed" && (
              <div className="text-center">
                <div className="w-20 h-20 rounded-full bg-destructive/10 flex items-center justify-center mx-auto mb-6">
                  <XCircle className="w-10 h-10 text-destructive" />
                </div>
                <h1 className="font-heading text-2xl font-bold text-foreground mb-2">
                  Booking Failed
                </h1>
                <p className="text-muted-foreground mb-4">
                  {errorMessage || "We couldn't complete your booking. Please try again or contact support."}
                </p>

                <div className="space-y-3">
                  <Button onClick={handleRetry} className="w-full">
                    Try Again
                  </Button>
                  <Button variant="outline" onClick={handleContactSupport} className="w-full">
                    Contact Support
                  </Button>
                  <Button variant="ghost" onClick={handleGoToDashboard} className="w-full">
                    Back to Dashboard
                  </Button>
                </div>

                {partnerOrderId && (
                  <p className="text-xs text-muted-foreground mt-4">
                    Reference: {partnerOrderId}
                  </p>
                )}
              </div>
            )}

            {/* Timeout State */}
            {status === "timeout" && (
              <div className="text-center">
                <div className="w-20 h-20 rounded-full bg-amber-500/10 flex items-center justify-center mx-auto mb-6">
                  <AlertTriangle className="w-10 h-10 text-amber-500" />
                </div>
                <h1 className="font-heading text-2xl font-bold text-foreground mb-2">
                  Taking Longer Than Expected
                </h1>
                <p className="text-muted-foreground mb-4">
                  Your booking is still being processed. This can happen during high demand periods.
                </p>

                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6 text-left">
                  <p className="text-sm text-amber-800">
                    <strong>Don't worry!</strong> Your booking request has been submitted. 
                    You'll receive an email confirmation once it's processed.
                  </p>
                </div>

                <div className="space-y-3">
                  <Button onClick={handleRetry} className="w-full">
                    Check Status Again
                  </Button>
                  <Button variant="outline" onClick={handleGoToDashboard} className="w-full">
                    Go to Dashboard
                  </Button>
                </div>

                {partnerOrderId && (
                  <p className="text-xs text-muted-foreground mt-4">
                    Order ID: {partnerOrderId}
                  </p>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </main>

      <Footer />
    </div>
  );
}
